---
- hosts: all
  become: true
  tasks:

  - name: install htop package
    community.general.apk:
      name: htop
      state: present
      update_cache: yes

  - name: install vim editor
    community.general.apk:
      name: vim
      state: present
      update_cache: yes

  - name: install git version control system
    community.general.apk:
      name: git
      state: present
      update_cache: yes

  - name: install nginx server
    community.general.apk:
      name: nginx
      state: present
      update_cache: yes

  - name: start and enable nginx server
    ansible.builtin.service:
      name: nginx
      enabled: false
      state: started

  - name: install python3 interpreter
    community.general.apk:
      name: python3
      state: present
      update_cache: yes

  - name: install tmux 
    community.general.apk:
      name: tmux
      state: present
      update_cache: yes
