---

- hosts: all
  become: true
  tasks:

    - name: Install docker containerd
      community.general.apk:
        name: docker
        state: present
        update_cache: yes

    - name: Start and enable docker service
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started
